const SUBJECTS=[
{id:'english',name:'English Language',board:'AQA 7702',sub:'Language, the individual and society · Diversity and change',topics:[['Textual variations & representations','Paper 1',72],['Children\'s language development','Paper 1',58],['Language diversity','Paper 2',68],['Language change','Paper 2',52],['Language discourses','Paper 2',61]]},
{id:'history',name:'History',board:'OCR H505',sub:'Y108 Early Stuarts · Y224 Apartheid & Reconciliation',topics:[['James I: monarchy & Parliament','Y108',64],['Charles I & Personal Rule, 1629–1640','Y108',39],['Origins & outbreak of Civil War','Y108',47],['Interregnum & Cromwell','Y108',59],['Resistance, repression & reform','Y224',51]]},
{id:'rs',name:'Religious Studies',board:'AQA 7062 · 2B',sub:'Christianity · Philosophy of religion · Ethics',topics:[['Sources of wisdom & authority','Christianity 2B',67],['Self, death & afterlife','Christianity 2B',54],['Arguments for the existence of God','Philosophy',48],['Problem of evil','Philosophy',57],['Normative ethical theories','Ethics',70]]}
];
const CARDS=[
['History','Why did Charles I rely on prerogative taxation during the Personal Rule?','Parliament was not sitting and ordinary Crown revenue was inadequate. Charles expanded devices such as Ship Money and forest fines to fund government without parliamentary taxation.'],
['History','Why was Ship Money politically dangerous even when collection initially succeeded?','It turned an emergency coastal levy into a national annual charge, making taxation a constitutional dispute about royal power without Parliament.'],
['English','What is the difference between language diversity and language change?','Diversity concerns variation between users and contexts at a given time; change concerns how language develops over time.'],
['RS','What makes the logical problem of evil different from the evidential problem?','The logical version claims God and evil are incompatible; the evidential version argues the amount or kinds of evil make God less probable.']
];
const STORAGE='revisionHQ_clean6';
const DEFAULT_STATE={streak:6,minutes:565,cards:74,dives:9,today:[['History · Personal Rule Deep Dive',30,false],['English · 8 retrieval cards',15,true],['RS · Problem of Evil essay plan',25,false]],week:[35,40,0,55,75,0,0],planner:[]};
let state=(()=>{try{const raw=localStorage.getItem(STORAGE);return raw?{...DEFAULT_STATE,...JSON.parse(raw)}:JSON.parse(JSON.stringify(DEFAULT_STATE));}catch(e){return JSON.parse(JSON.stringify(DEFAULT_STATE));}})();
let cardIndex=0,step=1,timer=1500,timerId=null,weekOffset=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch(e){}}function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function nav(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const m={overview:['REVISION HQ','Command Centre'],subjects:['CURRICULUM','Subjects'],deepdive:['ACTIVE RECALL','Deep Dive'],cards:['RETRIEVAL','Cards'],planner:['REVISION PLAN','Planner'],mastery:['EVIDENCE','Mastery']};$('#viewKicker').textContent=m[id][0];$('#viewTitle').textContent=m[id][1];window.scrollTo(0,0)}
$$('.nav').forEach(b=>b.onclick=()=>nav(b.dataset.view));$('#subjectsButton').onclick=()=>nav('subjects');$('#heroStart').onclick=$('#topStart').onclick=()=>nav('deepdive');
function allTopics(){return SUBJECTS.flatMap(s=>s.topics.map(t=>({subject:s.name,subjectId:s.id,name:t[0],unit:t[1],score:t[2]})))}
function renderOverview(){const ts=allTopics().sort((a,b)=>a.score-b.score),avg=Math.round(ts.reduce((a,t)=>a+t.score,0)/ts.length);$('#streakTop').textContent=state.streak+' days';$('#metricGrid').innerHTML=[['Mastery',avg+'%','across 15 mapped topics'],['Deep Dives',state.dives,'completed'],['Retrieval cards',state.cards,'scored'],['Focused time',Math.floor(state.minutes/60)+'h '+state.minutes%60+'m','logged']].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong><small>↑ ${x[2]}</small></div>`).join('');$('#priorityStack').innerHTML=ts.slice(0,5).map(t=>`<div class="priority-item"><div class="priority-score">${t.score}</div><div class="priority-copy"><strong>${t.name}</strong><span>${t.subject} · ${t.unit}</span></div><button class="priority-action">DEEP DIVE →</button></div>`).join('');$$('.priority-action').forEach(b=>b.onclick=()=>nav('deepdive'));renderToday();$('#weekChart').innerHTML=['M','T','W','T','F','S','S'].map((d,i)=>`<div class="day-bar ${i===3?'today':''}"><div class="bar" style="height:${Math.max(4,state.week[i])}px"></div>${d}</div>`).join('');$('#weeklyMinutes').textContent=state.week.reduce((a,b)=>a+b,0)+' min'}
function renderToday(){$('#todayTasks').innerHTML=state.today.map((t,i)=>`<div class="today-task ${t[2]?'done':''}"><button class="check" data-i="${i}">${t[2]?'✓':''}</button><span class="task-text">${t[0]}</span><span class="task-time">${t[1]}m</span></div>`).join('');$('#todayProgress').textContent=state.today.filter(x=>x[2]).length+' / '+state.today.length;$$('.check').forEach(b=>b.onclick=()=>{state.today[+b.dataset.i][2]=!state.today[+b.dataset.i][2];save();renderToday()})}
function renderSubjects(){$('#subjectGrid').innerHTML=SUBJECTS.map(s=>{const avg=Math.round(s.topics.reduce((a,t)=>a+t[2],0)/s.topics.length);return`<article class="subject-card" data-id="${s.id}"><small>${s.board}</small><h3>${s.name}</h3><p>${s.sub}</p><div class="meter"><i style="width:${avg}%"></i></div><p>${avg}% mastery · ${s.topics.length} topics</p></article>`}).join('');$$('.subject-card').forEach(c=>c.onclick=()=>showSubject(c.dataset.id))}
function showSubject(id){const s=SUBJECTS.find(x=>x.id===id);$('#topicDrawer').hidden=false;$('#topicDrawer').innerHTML=`<h3>${s.name}</h3>`+s.topics.map(t=>`<div class="topic-row"><span>${t[0]}<br><small>${t[1]}</small></span><b>${t[2]}%</b><button class="priority-action">Deep Dive</button></div>`).join('');$$('#topicDrawer .priority-action').forEach(b=>b.onclick=()=>nav('deepdive'))}
const anchors=['Ship Money became annual and was extended inland.','Hampden’s case made taxation a constitutional symbol.','Religious policies under Laud intensified opposition.','The Scottish crisis created military and financial pressure.','Charles had to recall Parliament in 1640.'];
function setStep(n){step=n;$$('.deep-step').forEach(e=>e.classList.toggle('active',+e.dataset.step===n));$('#deepStepNum').textContent=n;if(n===2)$('#anchorList').innerHTML=anchors.map(a=>`<div class="plan-item">${a}</div>`).join('');if(n===3)$('#confidenceButtons').innerHTML=['Still weak','Building','Secure'].map(x=>`<button type="button" class="ghost">${x}</button>`).join('')}
$('#commitRecall').onclick=()=>setStep(2);$('#commitRepair').onclick=()=>setStep(3);$('#finishDive').onclick=()=>{state.dives++;save();toast('Deep Dive completed');nav('overview');renderOverview()};
function renderCards(){const c=CARDS[cardIndex%CARDS.length];$('#cardSubject').textContent=c[0];$('#cardIndex').textContent=(cardIndex+1)+' / '+CARDS.length;$('#cardQuestion').textContent=c[1];$('#cardAnswer').textContent=c[2];$('#cardAnswer').hidden=true;$('#cardFooter').innerHTML='<button id="revealCard">Reveal answer</button>';$('#revealCard').onclick=()=>{$('#cardAnswer').hidden=false;$('#cardFooter').innerHTML='<button id="nextCard">Got it →</button>';$('#nextCard').onclick=()=>{state.cards++;cardIndex=(cardIndex+1)%CARDS.length;save();renderCards()}}}
function weekStart(){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7)+weekOffset*7);return d}function iso(d){return d.toISOString().slice(0,10)}function fmt(d){return d.toLocaleDateString('en-GB',{day:'numeric',month:'short'})}
function renderPlanner(){const mon=weekStart(),days=[0,1,2,3,4,5,6].map(i=>{const d=new Date(mon);d.setDate(mon.getDate()+i);return d});$('#weekRange').textContent=fmt(days[0])+' — '+fmt(days[6]);$('#plannerGrid').innerHTML=days.map((d,i)=>`<div class="day-col"><h4>${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}<br><small>${fmt(d)}</small></h4>${state.planner.filter(x=>x.date===iso(d)).map(x=>`<div class="plan-item"><b>${x.time}</b><br>${x.name}<br><small>${x.subject}</small></div>`).join('')}</div>`).join('')}
$('#prevWeek').onclick=()=>{weekOffset--;renderPlanner()};$('#nextWeek').onclick=()=>{weekOffset++;renderPlanner()};$('#todayWeek').onclick=()=>{weekOffset=0;renderPlanner()};
function openTutor(){$('#tutorModal').hidden=false;$('#tutorDate').value=iso(new Date())}function closeTutor(){$('#tutorModal').hidden=true}$('#addTutor').onclick=openTutor;$('#closeTutorModal').onclick=$('#cancelTutor').onclick=closeTutor;$('#tutorForm').onsubmit=e=>{e.preventDefault();state.planner.push({name:$('#tutorName').value,subject:$('#tutorSubject').value,date:$('#tutorDate').value,time:$('#tutorStart').value,duration:+$('#tutorDuration').value});save();closeTutor();renderPlanner();toast('Tutor session added')};
function renderMastery(){const ts=allTopics(),avg=Math.round(ts.reduce((a,t)=>a+t.score,0)/ts.length);$('#masterySummary').innerHTML=[['Overall mastery',avg+'%'],['Weak topics',ts.filter(t=>t.score<50).length],['Secure topics',ts.filter(t=>t.score>=68).length]].map(x=>`<div class="summary-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#masteryRows').innerHTML=ts.sort((a,b)=>a.score-b.score).map(t=>`<div class="mastery-row"><span>${t.subject}<br><small>${t.unit}</small></span><b>${t.name}</b><span>${t.score}%</span></div>`).join('')}
function countdown(){const target=new Date('2027-05-17T09:00:00'),ms=Math.max(0,target-Date.now()),d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);$('#daysToSeason').textContent=d;$('#countHours').textContent=String(h).padStart(2,'0');$('#countMinutes').textContent=String(m).padStart(2,'0');$('#countSeconds').textContent=String(s).padStart(2,'0')}function clock(){const m=Math.floor(timer/60),s=timer%60;$('#sessionTimer').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}$('#timerToggle').onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;$('#timerToggle').textContent='Start'}else{timerId=setInterval(()=>{timer=Math.max(0,timer-1);clock();if(!timer){clearInterval(timerId);timerId=null}},1000);$('#timerToggle').textContent='Pause'}};$('#timerReset').onclick=()=>{clearInterval(timerId);timerId=null;timer=1500;clock();$('#timerToggle').textContent='Start'};
$('#headerDate').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());renderOverview();renderSubjects();renderCards();renderPlanner();renderMastery();setStep(1);clock();countdown();setInterval(countdown,1000);