const KEY='revisionHQ_v8';
const todayKey=()=>new Date().toISOString().slice(0,10);
const defaults={streak:6,deepDives:9,cardsScored:74,focusedMinutes:565,weekMinutes:[35,40,0,55,75,0,0],topicScores:{},lastReviewed:{},completedToday:[],completedDate:todayKey(),planner:[],repairCards:[],deepHistory:[]};
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}}let state=load(),currentTopic='his-charles',deepStep=1,cardIndex=0,revealed=false,timer=1500,timerId=null,weekOffset=0,deepMarks={},deepConfidence=0,deepStartTs=0;state.repairCards=Array.isArray(state.repairCards)?state.repairCards:[];state.deepHistory=Array.isArray(state.deepHistory)?state.deepHistory:[];
if(state.completedDate!==todayKey()){state.completedToday=[];state.completedDate=todayKey();save()}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}function score(t){return state.topicScores[t.id]??t.score}function daysSince(t){return state.lastReviewed[t.id]??t.last}function need(t){return Math.round((100-score(t))*.55+Math.min(daysSince(t),21)*1.25+t.weight*7)}function ranked(){return [...TOPICS].sort((a,b)=>need(b)-need(a)||score(a)-score(b))}function topic(id){return TOPICS.find(t=>t.id===id)||TOPICS[0]}function subjectAvg(id){const ts=TOPICS.filter(t=>t.subject===id);return Math.round(ts.reduce((a,t)=>a+score(t),0)/ts.length)}function overall(){return Math.round(TOPICS.reduce((a,t)=>a+score(t),0)/TOPICS.length)}function status(s){return s<50?'weak':s<68?'building':'secure'}function statusLabel(s){return s<50?'Weak':s<68?'Building':'Secure'}function fmtTime(mins){return `${Math.floor(mins/60)}h ${String(mins%60).padStart(2,'0')}m`}function toast(text){const el=q('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1700)}
const views=['overview','subjects','deepdive','cards','planner','mastery'];function showView(id){if(!views.includes(id))id='overview';qa('.view').forEach(v=>v.classList.toggle('active',v.id===id));qa('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));q('#viewTitle').textContent={overview:'Command Centre',subjects:'Subjects',deepdive:'Deep Dive',cards:'Cards',planner:'Planner',mastery:'Mastery'}[id];window.scrollTo(0,0)}qa('.nav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));qa('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));
function renderOverview(){const top=ranked()[0],sub=SUBJECTS[top.subject];q('#heroTitle').innerHTML=`${sub.name}: ${top.name.replace(', 1629–1640','').replace('Charles I & Personal Rule','Charles I &<br>Personal Rule')}`;q('#heroCopy').textContent=top.copy||`Strengthen ${top.name} through active recall and exam application.`;q('#heroWhy').textContent=`Why now: ${score(top)}% mastery · ${daysSince(top)} days since review · high exam value`;q('#heroMeta').innerHTML=`◷ ${top.mins} min &nbsp;&nbsp; ◇ ${sub.board} · ${top.unit} &nbsp;&nbsp; ▥ Smart priority ${need(top)}`;q('#streakTop').textContent=`${state.streak} days`;
q('#metricGrid').innerHTML=`<div class="metric"><span>Mastery</span><strong>${overall()}%</strong><small>↑ across 15 mapped topics</small></div><div class="metric"><span>Deep Dives</span><strong>${state.deepDives}</strong><small>↑ completed</small></div><div class="metric"><span>Retrieval cards</span><strong>${state.cardsScored}</strong><small>↑ scored</small></div><div class="metric"><span>Focused time</span><strong>${fmtTime(state.focusedMinutes)}</strong><small>↑ logged</small></div>`;
q('#priorityStack').innerHTML=ranked().slice(0,5).map(t=>`<div class="priority-item"><div class="score">${score(t)}</div><div class="priority-copy"><b>${t.name}</b><small>${SUBJECTS[t.subject].name} · ${t.unit} · ${daysSince(t)}d since review</small></div><button class="mini-action" data-topic="${t.id}">DEEP DIVE →</button></div>`).join('');qa('.mini-action').forEach(b=>b.addEventListener('click',()=>openDeep(b.dataset.topic)));
const daily=ranked().slice(0,3).map((t,i)=>({id:t.id,topic:t,method:['Deep Dive','Retrieval cards','Exam plan'][i],mins:[30,15,25][i]}));q('#todayTasks').innerHTML=daily.map(d=>{const done=state.completedToday.includes(d.id);return `<div class="today-row ${done?'done':''}" data-task="${d.id}"><button class="tick">${done?'✓':''}</button><span class="today-text">${SUBJECTS[d.topic.subject].name} · ${d.topic.name}<span class="today-reason">${d.method} · priority ${need(d.topic)}</span></span><span class="today-time">${d.mins}m</span></div>`}).join('');qa('.tick').forEach(b=>b.addEventListener('click',()=>{const id=b.closest('[data-task]').dataset.task;state.completedToday=state.completedToday.includes(id)?state.completedToday.filter(x=>x!==id):[...state.completedToday,id];save();renderOverview()}));q('#todayProgress').textContent=`${daily.filter(d=>state.completedToday.includes(d.id)).length} / 3`;
const day=(new Date().getDay()+6)%7,total=state.weekMinutes.reduce((a,b)=>a+b,0);q('#weekChart').innerHTML=['M','T','W','T','F','S','S'].map((d,i)=>`<div class="daybar ${i===day?'today':''}"><div class="bar" style="height:${Math.max(4,Math.min(86,state.weekMinutes[i]))}px"></div>${d}</div>`).join('');q('#weeklyMinutes').textContent=`${total} min`;q('#weekDone').textContent=`${state.weekMinutes.filter(v=>v>=20).length} complete`;q('#stripEnglish').textContent=`${subjectAvg('english')}% mastery`;q('#stripHistory').textContent=`${subjectAvg('history')}% mastery`;q('#stripRS').textContent=`${subjectAvg('rs')}% mastery`;q('#cardsStat').textContent=state.cardsScored}
function renderSubjects(){q('#subjectGrid').innerHTML=Object.entries(SUBJECTS).map(([id,s])=>{const ts=TOPICS.filter(t=>t.subject===id),avg=subjectAvg(id),weak=[...ts].sort((a,b)=>score(a)-score(b)).slice(0,3);return `<article class="subject-card"><div class="subject-topline"><div><small>${s.board}</small><h3>${s.name}</h3></div><div class="subject-score">${avg}%</div></div><p>${s.subtitle}</p><div class="meter"><i style="width:${avg}%"></i></div><div class="topic-list">${weak.map(t=>`<div class="topic"><span>${t.name}</span><b class="topic-status ${status(score(t))}">${statusLabel(score(t))} · ${score(t)}%</b></div>`).join('')}</div></article>`}).join('')}
function deepMaterial(t){return DEEP_MATERIAL[t.id]||{prompt:`Without notes, explain the most important causes, evidence and consequences for ${t.name}.`,anchors:[['Core issue',`Define the central issue in ${t.name}.`],['Precise evidence','Identify two specific examples, quotations, events or concepts.'],['Connection','Explain why the evidence matters rather than simply listing it.'],['Counterweight','Include a limitation, alternative factor or competing interpretation.']],exam:`Plan an exam response on ${t.name}: judgement + three argument blocks + strongest evidence.`,focus:'Move from accurate knowledge to a clear, comparative judgement.'}}
function wordCount(v){return (String(v||'').trim().match(/\S+/g)||[]).length}