const q=s=>document.querySelector(s),qa=s=>Array.from(document.querySelectorAll(s));
const SUBJECTS={english:{name:'English Language',board:'AQA 7702',subtitle:'Language, the individual and society · Diversity and change'},history:{name:'History',board:'OCR H505',subtitle:'Y108 Early Stuarts · Y224 Apartheid & Reconciliation'},rs:{name:'Religious Studies',board:'AQA 7062 · 2B',subtitle:'Christianity · Philosophy of religion · Ethics'}};
const TOPICS=[
{id:'his-charles',subject:'history',unit:'Y108',name:'Charles I & Personal Rule, 1629–1640',score:39,last:15,weight:3,mins:30,copy:'Explore the causes, key policies and the growing opposition to Charles I, 1629–1640.'},
{id:'his-war',subject:'history',unit:'Y108',name:'Origins & outbreak of Civil War',score:47,last:11,weight:3,mins:30},
{id:'his-apartheid',subject:'history',unit:'Y224',name:'Creation & consolidation of apartheid',score:56,last:7,weight:2,mins:25},
{id:'his-resistance',subject:'history',unit:'Y224',name:'Resistance, repression & reform',score:51,last:10,weight:3,mins:25},
{id:'his-transition',subject:'history',unit:'Y224',name:'Negotiation, transition & reconciliation',score:69,last:4,weight:2,mins:25},
{id:'eng-rep',subject:'english',unit:'Paper 1',name:'Textual variations & representations',score:72,last:3,weight:3,mins:20},
{id:'eng-child',subject:'english',unit:'Paper 1',name:"Children's language development",score:58,last:8,weight:2,mins:20},
{id:'eng-div',subject:'english',unit:'Paper 2',name:'Language diversity',score:68,last:5,weight:2,mins:20},
{id:'eng-change',subject:'english',unit:'Paper 2',name:'Language change',score:52,last:12,weight:3,mins:20},
{id:'eng-write',subject:'english',unit:'Paper 2',name:'Opinion / persuasive writing',score:66,last:6,weight:2,mins:20},
{id:'rs-god',subject:'rs',unit:'Christianity 2B',name:'Sources of wisdom & authority',score:67,last:5,weight:2,mins:20},
{id:'rs-self',subject:'rs',unit:'Christianity 2B',name:'Self, death & afterlife',score:54,last:9,weight:2,mins:20},
{id:'rs-arguments',subject:'rs',unit:'Philosophy',name:'Arguments for the existence of God',score:48,last:13,weight:3,mins:25},
{id:'rs-evil',subject:'rs',unit:'Philosophy',name:'Problem of evil',score:57,last:10,weight:3,mins:25},
{id:'rs-ethics',subject:'rs',unit:'Ethics',name:'Normative ethical theories',score:70,last:4,weight:2,mins:25}
];
const CARDS=[
{topic:'his-charles',q:'Why did Charles I rely on prerogative taxation during the Personal Rule?',a:'Parliament was not sitting and ordinary Crown revenue was inadequate. Charles expanded devices such as Ship Money and forest fines to fund government without parliamentary taxation.'},
{topic:'his-charles',q:'Why was Ship Money politically dangerous even when collection initially succeeded?',a:'It turned an emergency levy into a constitutional dispute about whether the king could tax without Parliament.'},
{topic:'eng-change',q:'What is the difference between language diversity and language change?',a:'Diversity concerns variation between users and contexts at a given time; change concerns how language develops over time.'},
{topic:'rs-evil',q:'What makes the logical problem of evil different from the evidential problem?',a:'The logical version claims God and evil are incompatible; the evidential version argues the amount or kinds of evil make God less probable.'}
];
const DEEP_MATERIAL={
'his-charles':{prompt:"Why did Charles I's Personal Rule create serious political and financial tension by 1640?",anchors:[['Ship Money','Ship Money became annual and was extended beyond coastal counties, making royal finance a constitutional issue.'],['Hampden','John Hampden’s 1637 case turned resistance to Ship Money into a national political symbol.'],['Laudian religion','Laud’s ceremonial reforms and enforcement deepened fears of Catholic-style innovation and arbitrary government.'],['Scottish crisis','The 1637 Prayer Book crisis led to rebellion and the Bishops’ Wars, creating military and financial pressure.'],['Recall Parliament','Unable to finance war sustainably, Charles recalled Parliament in 1640, ending the Personal Rule.']],exam:'“Financial weakness was the main reason Charles I\'s Personal Rule collapsed.” Assess this view.',focus:'Weigh finance against religion and the Scottish crisis; do not treat them as separate stories.'},
'his-war':{prompt:'Why did political tension turn into civil war in 1642 rather than being resolved after 1640?',anchors:[['Trust collapsed','The legacy of Personal Rule meant Parliament doubted Charles would honour a lasting settlement.'],['Grand Remonstrance','The Grand Remonstrance exposed deep divisions over religion, royal advisers and the future balance of power.'],['Five Members','Charles’s failed attempt to arrest the Five Members in January 1642 destroyed confidence in his intentions.'],['Militia dispute','Control of the militia became decisive because both sides feared the other would use armed force.'],['Competing legitimacy','By summer 1642 king and Parliament each claimed constitutional authority, making compromise increasingly difficult.']],exam:'“Religious division was more important than constitutional conflict in causing the outbreak of Civil War in 1642.” Assess this view.',focus:'Build a chain from distrust to specific flashpoints to the final contest over armed power.'},
'his-apartheid':{prompt:'How and why did the National Party turn segregation into a more systematic apartheid state after 1948?',anchors:[['1948 victory','The National Party victory gave political authority to a programme of stricter racial separation.'],['Population Registration','Racial classification underpinned the administration of rights, residence and movement.'],['Group Areas','Residential segregation was enforced through Group Areas legislation and forced removals.'],['Pass controls','Pass laws and influx control restricted Black South Africans’ movement and access to urban areas.'],['Bantu Education','Education policy aimed to reproduce racial hierarchy and limit economic and political opportunity.']],exam:'“Apartheid after 1948 was mainly an extension of earlier segregation.” Assess this view.',focus:'Distinguish continuity from the greater legal coherence, reach and enforcement of apartheid.'},
'his-resistance':{prompt:'Why did resistance to apartheid change in form and intensity from the 1950s to the 1980s?',anchors:[['Mass mobilisation','The Defiance Campaign and Freedom Charter era expanded organised mass resistance.'],['Sharpeville','Sharpeville in 1960 exposed state violence and helped push resistance towards underground and armed strategies.'],['State repression','Banning, imprisonment and security legislation weakened formal opposition while radicalising parts of it.'],['Soweto','The 1976 Soweto uprising revealed a new generation of resistance and the influence of Black Consciousness.'],['1980s pressure','Township revolt, unions, civic organisations and international pressure combined to make apartheid harder to govern.']],exam:'“State repression strengthened rather than weakened resistance to apartheid.” Assess this view.',focus:'Track how repression changed methods of resistance rather than assuming a simple rise or fall.'},
'his-transition':{prompt:'Why did South Africa move from apartheid towards negotiated majority rule between 1989 and 1994?',anchors:[['De Klerk reforms','De Klerk unbanned liberation movements and released Nelson Mandela in 1990.'],['Negotiation','CODESA and later negotiations established a route towards a new constitutional order despite breakdowns.'],['Violence','Political violence threatened the process and shaped bargaining over security and legitimacy.'],['Economic pressure','Economic weakness, sanctions and international isolation reduced the sustainability of apartheid.'],['1994 election','The 1994 election transferred political authority through a negotiated democratic settlement.']],exam:'“F. W. de Klerk was the decisive factor in South Africa’s transition to democracy.” Assess this view.',focus:'Compare leadership with structural pressure and the leverage of the ANC and mass politics.'},
'eng-rep':{prompt:'How should an AQA Language student move from identifying language features to analysing representation?',anchors:[['Pattern first','Move beyond isolated labels and identify recurring lexical, grammatical or discourse patterns.'],['Representation','Explain how those patterns construct people, groups, events, relationships or identities.'],['Context','Relate choices to audience, purpose, genre, mode and relevant social context.'],['Methods + effects','Use linguistic terminology to explain meaning rather than treating terminology as the analysis itself.'],['Comparison','When comparing, focus on meaningful similarities and differences in how representations are built.']],exam:'Plan a comparative response explaining how two texts construct contrasting representations of authority.',focus:'Every paragraph should move method → pattern → representation → context, not feature spotting.'},
'eng-child':{prompt:'What evidence and concepts would you use to explain how children develop language rather than simply describing their speech?',anchors:[['Stages not cages','Developmental stages are useful patterns, but children vary and development is not perfectly linear.'],['Interaction','Caregiver interaction, feedback, turn-taking and child-directed speech can support development.'],['Cognition','Cognitive development affects categorisation, memory, symbolic thought and the meanings children can express.'],['Grammar growth','Track changes in morphology and syntax, not only vocabulary size.'],['Theory evaluation','Use data to evaluate theoretical explanations rather than attaching theorists after the analysis.']],exam:'Plan a response to the view that children acquire language mainly through interaction with caregivers.',focus:'Use language data as evidence for or against explanations; theory should answer the data.'},
'eng-div':{prompt:'How can you explain language diversity without falling into stereotypes about accent, class, gender or region?',anchors:[['Variation is patterned','Language varies systematically across users, groups, contexts and identities.'],['Identity is performed','Speakers can use features to construct affiliation, stance and identity rather than merely reflecting a fixed category.'],['Context matters','Style-shifting and audience design show that one speaker can vary across situations.'],['Attitudes matter','Prestige and stigma are social judgements, not inherent properties of a variety.'],['Evidence over stereotype','Use studies and data cautiously; avoid claiming every member of a group speaks in the same way.']],exam:'Plan a response to the claim that social class is the most important influence on the way people use language.',focus:'Treat social variables as interacting influences and keep returning to actual language evidence.'},
'eng-change':{prompt:'Why does language change, and how should you evaluate claims that change means decline?',anchors:[['Multiple causes','Change can arise through contact, technology, social change, innovation, analogy and changing identities.'],['Lexical change','New words, semantic shifts and borrowing are visible but are only one level of change.'],['Grammar and sound','Change can also affect morphology, syntax, pronunciation and discourse conventions.'],['Attitudes','Complaints about decline often reflect prescriptivism, identity and social anxiety.'],['Processes spread','Innovations spread unevenly through communities and may coexist with older forms for long periods.']],exam:'Plan a response to the view that technology is the main cause of language change in the twenty-first century.',focus:'Separate evidence of change from attitudes towards change, then weigh causes.'},
'eng-write':{prompt:'What makes persuasive or opinion writing effective at A Level beyond using a list of rhetorical devices?',anchors:[['Clear position','Establish a purposeful viewpoint and sustain it rather than sounding neutral or indecisive.'],['Audience design','Choose register, assumptions and forms of address for the intended audience and genre.'],['Structure','Sequence ideas deliberately so the argument develops rather than becoming a series of points.'],['Voice','Create a controlled, distinctive voice through syntax, lexis, rhythm and stance.'],['Methods serve purpose','Rhetorical techniques should sharpen reasoning or engagement, not appear as decorative devices.']],exam:'Plan the opening, argument arc and ending of an opinion article arguing that schools should teach more about language prejudice.',focus:'Design the whole piece around audience and purpose; devices are subordinate to the argument.'},
'rs-god':{prompt:'How do sources of wisdom and authority shape Christian belief and practice, and why can they produce disagreement?',anchors:[['Bible','Scripture is foundational but Christians disagree about interpretation, genre and authority.'],['Jesus','The teaching and example of Jesus provide a central lens for Christian ethics and belief.'],['Church tradition','Tradition, councils and denominational authority matter differently across Christian communities.'],['Reason and conscience','Reason, experience and conscience can shape how inherited teaching is applied.'],['Interpretive conflict','Disagreement often comes from competing authorities or different ways of interpreting the same source.']],exam:'“The Bible should be the only source of authority for Christians.” Evaluate this claim.',focus:'Evaluation requires comparing sources of authority and showing how interpretation changes conclusions.'},
'rs-self':{prompt:'What are the main Christian ideas about the self, death and afterlife, and where do tensions arise?',anchors:[['Human nature','Christian accounts often connect human worth to creation in the image of God while recognising sin and moral failure.'],['Soul and body','Traditions differ over how soul, body and personal identity relate after death.'],['Resurrection','Bodily resurrection is central to historic Christian teaching and differs from a simple idea of an immortal soul escaping the body.'],['Judgement','Judgement links afterlife beliefs to moral responsibility, grace and salvation.'],['Heaven and hell','Interpretations range from literal to symbolic, creating debate about justice, mercy and eternal destiny.']],exam:'“Belief in bodily resurrection is more important than belief in an immortal soul.” Evaluate this claim.',focus:'Define the concepts precisely before evaluating their coherence and religious significance.'},
'rs-arguments':{prompt:'How do the main arguments for God move from features of the world to a conclusion about divine existence?',anchors:[['Cosmological','Cosmological arguments reason from contingency, causation or dependence towards a necessary foundation.'],['Teleological','Design arguments infer purpose or intelligence from order, complexity or fine-tuning.'],['Ontological','Ontological reasoning is a priori: it works from the concept of God rather than observation of the world.'],['Challenges','Hume, Kant and later critics question causal inference, design analogy and whether existence can function as a predicate.'],['Evaluation','Even if an argument succeeds, ask what kind of God it establishes and whether the conclusion is stronger than the premises allow.']],exam:'“The cosmological argument gives no good reason to believe in the God of classical theism.” Evaluate this claim.',focus:'Do not just describe arguments and objections; judge whether the conclusion follows and what it establishes.'},
'rs-evil':{prompt:'Why is evil considered a serious challenge to belief in an omnipotent, omniscient and perfectly good God?',anchors:[['Logical problem','The logical problem argues that traditional divine attributes and the existence of evil are inconsistent.'],['Evidential problem','The evidential problem argues that the amount or kinds of suffering make God’s existence less probable.'],['Free will','Free-will defences explain moral evil through genuinely free creatures but face questions about natural evil.'],['Soul-making','Irenaean or Hick-style approaches see a challenging world as necessary for moral and spiritual development.'],['Protest and limits','Critics question whether extreme or apparently pointless suffering can be justified by greater-good explanations.']],exam:'“The free-will defence successfully solves the problem of evil.” Evaluate this claim.',focus:'Distinguish defence from theodicy and test each response against both moral and natural evil.'},
'rs-ethics':{prompt:'How do major normative ethical theories decide what makes an action right, and where do they conflict?',anchors:[['Natural law','Natural law grounds morality in human nature, reason and objective goods or purposes.'],['Situation ethics','Situation ethics prioritises agape and flexible judgement over absolute rules.'],['Utilitarianism','Utilitarian approaches judge actions by consequences for wellbeing or utility.'],['Kantian ethics','Kantian ethics emphasises duty, universal principles and respect for persons rather than outcomes.'],['Application exposes differences','Theories become clearest when applied to the same dilemma and compared for consistency, flexibility and moral plausibility.']],exam:'“Consequences are the only reliable basis for moral decision-making.” Evaluate this claim.',focus:'Compare theories on the same moral problem rather than evaluating each in isolation.'}
};