function openDeep(id){currentTopic=id;deepStep=1;deepMarks={};deepConfidence=0;deepStartTs=Date.now();q('#brainDump').value='';q('#gapBox').value='';q('#examPlan').value='';q('#deepCompletion').classList.remove('active');qa('.deep-step').forEach(x=>x.style.display='');renderDeep();showView('deepdive');updateDeepInputs()}
function renderDeep(){const t=topic(currentTopic),s=SUBJECTS[t.subject],m=deepMaterial(t);q('#deepBoard').textContent=`${s.board.toUpperCase()} · ${t.unit}`;q('#deepTopic').textContent=t.name;q('#deepPrompt').textContent=m.prompt;q('#whyTopic').textContent=`Revision HQ ranks this topic at ${need(t)} because it combines current mastery, recency and exam importance.`;q('#reasonList').innerHTML=`<span>Current mastery · ${score(t)}%</span><span>Last reviewed · ${daysSince(t)} days ago</span><span>Exam weighting · ${'●'.repeat(t.weight)}${'○'.repeat(3-t.weight)}</span>`;q('#coachText').textContent=m.focus;q('#anchorList').innerHTML=m.anchors.map((a,i)=>`<div class="evidence-item" data-anchor="${i}"><div class="evidence-num">${i+1}</div><div class="evidence-copy"><b>${a[0]}</b><small>${a[1]}</small></div><div class="evidence-actions"><button type="button" data-mark="have" data-anchor="${i}">Had it</button><button type="button" data-mark="miss" data-anchor="${i}">Missed it</button></div></div>`).join('');q('#examQuestion').textContent=m.exam;q('#repairStack').innerHTML='<div class="repair-gap"><strong>Not checked yet.</strong> Mark the evidence anchors first.</div>';q('#repairCardText').textContent='Your missed evidence will become a retrieval prompt.';qa('#confidenceButtons button').forEach(b=>b.classList.remove('selected'));bindEvidenceButtons();setDeep(1);updateCoverage()}
function setDeep(n){deepStep=n;qa('.deep-step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===n));q('#deepStepNum').textContent=n;qa('.stage-pill').forEach(x=>{const s=Number(x.dataset.stage);x.classList.toggle('on',s===n);x.classList.toggle('done',s<n)});q('#deepCompletion').classList.remove('active');updateDeepInputs()}
function bindEvidenceButtons(){qa('[data-mark]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.anchor);deepMarks[i]=b.dataset.mark;const item=q(`.evidence-item[data-anchor="${i}"]`);item.classList.toggle('mark-have',deepMarks[i]==='have');item.classList.toggle('mark-miss',deepMarks[i]==='miss');item.querySelectorAll('button').forEach(x=>{x.classList.toggle('selected-have',x.dataset.mark==='have'&&deepMarks[i]==='have');x.classList.toggle('selected-miss',x.dataset.mark==='miss'&&deepMarks[i]==='miss')});updateCoverage()}))}
function updateCoverage(){const m=deepMaterial(topic(currentTopic)),total=m.anchors.length,marked=Object.keys(deepMarks).length,have=Object.values(deepMarks).filter(x=>x==='have').length;q('#coverageScore').textContent=`${have} / ${total}`;q('#coverageFill').style.width=`${Math.round(have/total*100)}%`;q('#commitCheck').disabled=marked<total}
function buildRepair(){const m=deepMaterial(topic(currentTopic));const misses=m.anchors.map((a,i)=>deepMarks[i]==='miss'?a:null).filter(Boolean);q('#repairIntro').textContent=misses.length?`You identified ${misses.length} gap${misses.length===1?'':'s'}. Repair those only — do not rewrite the whole topic.`:'You recalled every anchor. Use the repair box to state the single connection you most want to make automatic under exam pressure.';q('#repairStack').innerHTML=misses.length?misses.map(a=>`<div class="repair-gap"><strong>${a[0]}:</strong> ${a[1]}</div>`).join(''):'<div class="repair-gap" style="border-left-color:var(--green)"><strong style="color:var(--green)">No anchor gaps.</strong> Strengthen the causal or evaluative connection that would make your answer sharper.</div>';q('#repairCardText').textContent=misses.length?`Prompt: What did you miss about ${misses.map(x=>x[0]).join(', ')}?\nAnswer: ${misses.map(x=>x[1]).join(' ')} `:`Prompt: What is the strongest evaluative connection in ${topic(currentTopic).name}?`;updateDeepInputs()}
function updateDeepInputs(){const rw=wordCount(q('#brainDump')?.value),gw=wordCount(q('#gapBox')?.value),pw=wordCount(q('#examPlan')?.value);if(q('#recallWords'))q('#recallWords').textContent=`${rw} words`;if(q('#repairWords'))q('#repairWords').textContent=`${gw} words`;if(q('#planWords'))q('#planWords').textContent=`${pw} words`;if(q('#recallHint'))q('#recallHint').textContent=rw<15?'Get the first facts down.':rw<40?'Good start — add connections or evidence.':'Enough to expose real gaps.';if(q('#repairHint'))q('#repairHint').textContent=gw<15?'Explain the missing link in your own words.':gw<35?'Good — make the causal/evaluative connection explicit.':'Repair captured.';if(q('#planHint'))q('#planHint').textContent=pw<20?'Start with a judgement.':pw<55?'Add precise evidence and a counterweight.':'Strong enough to score.'}
['brainDump','gapBox','examPlan'].forEach(id=>q('#'+id).addEventListener('input',updateDeepInputs));
q('#commitRecall').addEventListener('click',()=>{if(wordCount(q('#brainDump').value)<8){toast('Put down a little more from memory first.');return}setDeep(2)});
q('#backRecall').addEventListener('click',()=>setDeep(1));
q('#commitCheck').addEventListener('click',()=>{buildRepair();setDeep(3)});
q('#backCheck').addEventListener('click',()=>setDeep(2));
q('#commitRepair').addEventListener('click',()=>{const misses=Object.values(deepMarks).filter(x=>x==='miss').length;if(misses&&wordCount(q('#gapBox').value)<8){toast('Explain the gap in your own words before moving on.');return}setDeep(4)});
q('#backRepair').addEventListener('click',()=>setDeep(3));
qa('#confidenceButtons button').forEach(b=>b.addEventListener('click',()=>{deepConfidence=Number(b.dataset.confidence);qa('#confidenceButtons button').forEach(x=>x.classList.toggle('selected',x===b))}));
q('#finishDive').addEventListener('click',()=>{if(wordCount(q('#examPlan').value)<12){toast('Add a judgement and at least one evidence-led argument.');return}if(!deepConfidence){toast('Choose how secure this feels under exam conditions.');return}completeDeepDive()});
function completeDeepDive(){const t=topic(currentTopic),m=deepMaterial(t),before=score(t),total=m.anchors.length,have=Object.values(deepMarks).filter(x=>x==='have').length,misses=total-have,coverage=have/total,repairWords=wordCount(q('#gapBox').value),planWords=wordCount(q('#examPlan').value);let gain=2+Math.round(coverage*3)+(repairWords>=15?1:0)+(planWords>=35?1:0)+(deepConfidence>=3?1:0);gain=Math.max(2,Math.min(8,gain));const after=Math.min(95,before+gain),actualGain=after-before;state.topicScores[t.id]=after;state.lastReviewed[t.id]=0;state.deepDives++;const elapsed=Math.max(5,Math.round((Date.now()-deepStartTs)/60000));const credited=Math.min(Math.max(elapsed,10),t.mins||30);state.focusedMinutes+=credited;const day=(new Date().getDay()+6)%7;state.weekMinutes[day]=(state.weekMinutes[day]||0)+credited;if(!state.completedToday.includes(t.id))state.completedToday.push(t.id);const missed=m.anchors.filter((a,i)=>deepMarks[i]==='miss');if(missed.length){state.repairCards.unshift({topic:t.id,created:Date.now(),prompt:`What did you miss about ${missed.map(x=>x[0]).join(', ')}?`,answer:missed.map(x=>x[1]).join(' ')});state.repairCards=state.repairCards.slice(0,20)}state.deepHistory.unshift({topic:t.id,date:Date.now(),coverage:Math.round(coverage*100),gaps:misses,gain:actualGain,confidence:deepConfidence});state.deepHistory=state.deepHistory.slice(0,40);save();renderAll();const reviewDays=after<50?2:after<68?4:7;q('#summaryCoverage').textContent=`${Math.round(coverage*100)}%`;q('#summaryGaps').textContent=misses;q('#summaryGain').textContent=`+${actualGain}`;q('#summaryConfidence').textContent=['','Shaky','Building','Secure','Strong'][deepConfidence];q('#completionLine').textContent=misses?`You found ${misses} real gap${misses===1?'':'s'}, repaired ${misses===1?'it':'them'}, and then applied the topic to an exam move.`:'Your recall was strong across every anchor. The application stage still added exam evidence.';q('#summaryNext').innerHTML=`<strong>Next review: in ${reviewDays} days.</strong> ${missed.length?'A repair card has been saved from the evidence you missed.':'Revision HQ will bring this topic back through normal retrieval.'} Mastery moved from ${before}% to ${after}%.`;qa('.deep-step').forEach(x=>x.classList.remove('active'));q('#deepCompletion').classList.add('active');qa('.stage-pill').forEach(x=>{x.classList.remove('on');x.classList.add('done')});q('#deepStepNum').textContent='✓';toast('Deep Dive complete · evidence recorded')}
q('#returnCommand').addEventListener('click',()=>showView('overview'));q('#anotherDive').addEventListener('click',()=>{const next=ranked().find(x=>x.id!==currentTopic)||ranked()[0];openDeep(next.id)});q('#heroStart').addEventListener('click',()=>openDeep(ranked()[0].id));q('#topStart').addEventListener('click',()=>openDeep(ranked()[0].id));