(()=>{'use strict';
const q=s=>document.querySelector(s),qa=s=>Array.from(document.querySelectorAll(s));
const KEY='revisionHQ_v8',todayKey=()=>new Date().toISOString().slice(0,10);
const TOPICS=[
{id:'his-charles',subject:'History',unit:'Y108',name:'Charles I & Personal Rule, 1629–1640',score:39,last:15,weight:3},
{id:'his-war',subject:'History',unit:'Y108',name:'Origins & outbreak of Civil War',score:47,last:11,weight:3},
{id:'his-apartheid',subject:'History',unit:'Y224',name:'Creation & consolidation of apartheid',score:56,last:7,weight:2},
{id:'his-resistance',subject:'History',unit:'Y224',name:'Resistance, repression & reform',score:51,last:10,weight:3},
{id:'his-transition',subject:'History',unit:'Y224',name:'Negotiation, transition & reconciliation',score:69,last:4,weight:2},
{id:'eng-rep',subject:'English Language',unit:'Paper 1',name:'Textual variations & representations',score:72,last:3,weight:3},
{id:'eng-child',subject:'English Language',unit:'Paper 1',name:"Children's language development",score:58,last:8,weight:2},
{id:'eng-div',subject:'English Language',unit:'Paper 2',name:'Language diversity',score:68,last:5,weight:2},
{id:'eng-change',subject:'English Language',unit:'Paper 2',name:'Language change',score:52,last:12,weight:3},
{id:'eng-write',subject:'English Language',unit:'Paper 2',name:'Opinion / persuasive writing',score:66,last:6,weight:2},
{id:'rs-god',subject:'Religious Studies',unit:'Christianity 2B',name:'Sources of wisdom & authority',score:67,last:5,weight:2},
{id:'rs-self',subject:'Religious Studies',unit:'Christianity 2B',name:'Self, death & afterlife',score:54,last:9,weight:2},
{id:'rs-arguments',subject:'Religious Studies',unit:'Philosophy',name:'Arguments for the existence of God',score:48,last:13,weight:3},
{id:'rs-evil',subject:'Religious Studies',unit:'Philosophy',name:'Problem of evil',score:57,last:10,weight:3},
{id:'rs-ethics',subject:'Religious Studies',unit:'Ethics',name:'Normative ethical theories',score:70,last:4,weight:2}
];
const BANK={
'his-charles':{prompt:'Three bullets. Why did Personal Rule become unsustainable by 1640?',anchors:['Ship Money and other prerogative finance created constitutional opposition.','Laudian religious policy intensified fears about arbitrary rule and Catholicism.','The Scottish crisis forced military spending and ultimately the recall of Parliament.']},
'his-war':{prompt:'What turned political conflict into civil war in 1641–42?',anchors:['Trust collapsed over control of armed force and the militia.','The Grand Remonstrance exposed deep divisions over religion and royal power.','The attempted arrest of the Five Members and competing military mobilisation made compromise far harder.']},
'his-apartheid':{prompt:'What made apartheid after 1948 more than earlier segregation?',anchors:['The National Party made racial separation a more systematic state programme.','Population Registration and Group Areas classified people and organised space by race.','Pass controls, education and labour rules embedded racial hierarchy in daily life.']},
'his-resistance':{prompt:'What made resistance to apartheid increasingly difficult to contain?',anchors:['ANC/PAC mobilisation and mass protest widened opposition.','State repression after Sharpeville pushed resistance into new forms, including armed struggle.','Soweto, international pressure and economic costs weakened the regime’s ability to sustain the system.']},
'his-transition':{prompt:'Why did South Africa move from apartheid to negotiated transition?',anchors:['De Klerk unbanned liberation movements and released Mandela in 1990.','Negotiations advanced despite political violence and repeated breakdowns.','The 1994 election and later TRC sought democratic legitimacy and reconciliation.']},
'eng-rep':{prompt:'What makes a strong representation analysis rather than feature spotting?',anchors:['Identify patterns of lexical, grammatical and discourse choices rather than isolated techniques.','Explain how those patterns construct people, events or relationships.','Link representation to audience, purpose, genre and context.']},
'eng-child':{prompt:'What should a strong child-language answer connect together?',anchors:['Use precise developmental evidence from phonology, lexis, grammar or pragmatics.','Consider interaction with caregivers, including modelling and scaffolding.','Evaluate theoretical explanations rather than presenting one theory as sufficient.']},
'eng-div':{prompt:'What are the three moves in a strong language-diversity argument?',anchors:['Identify variation linked to region, social group, occupation or identity.','Explain accommodation, code-switching or audience design where relevant.','Analyse attitudes to varieties, including prescriptive and descriptive judgements.']},
'eng-change':{prompt:'What drives language change, and how should you evaluate it?',anchors:['Track lexical, semantic, grammatical or phonological change with precise examples.','Separate internal language processes from social, technological and cultural pressures.','Evaluate attitudes to change rather than assuming change equals decline.']},
'eng-write':{prompt:'What makes persuasive writing controlled rather than simply “rhetorical”?',anchors:['Make audience, purpose and genre drive language choices.','Use structure and patterning to control emphasis and progression.','Create a consistent stance and representation rather than stacking techniques.']},
'rs-god':{prompt:'How can Christian authority be justified when sources appear to conflict?',anchors:['Scripture is central but interpretation differs between traditions.','Church tradition and teaching can shape how scripture is understood.','Reason and experience may support or challenge particular interpretations.']},
'rs-self':{prompt:'What needs comparing in Christian views of self, death and afterlife?',anchors:['Different accounts of soul, resurrection and personal identity matter.','Judgement, heaven and hell are interpreted differently across traditions.','Beliefs about afterlife shape ethical behaviour and understandings of salvation.']},
'rs-arguments':{prompt:'How do you turn an argument for God into an evaluative paragraph?',anchors:['State the argument’s key premise and inferential move precisely.','Use a focused objection that attacks a premise or the inference.','Judge whether the objection defeats the argument or merely limits its force.']},
'rs-evil':{prompt:'What are the key distinctions needed in an essay on evil?',anchors:['Distinguish the logical problem from the evidential problem of evil.','Explain a theodicy or defence such as free will or soul-making accurately.','Evaluate whether the response addresses natural as well as moral evil and the scale of suffering.']},
'rs-ethics':{prompt:'What makes comparison of ethical theories analytical?',anchors:['State the decision rule or central principle of each theory clearly.','Apply each theory to the same moral pressure point.','Evaluate consistency, consequences and the role of character or intention.']}
};
const defaults={xp:1180,missionCount:6,missionBests:{},missionLog:[],lastMissionTopic:'',weekMinutes:[35,40,0,55,75,0,0],topicScores:{},lastReviewed:{},completedToday:[],completedDate:todayKey(),focusedMinutes:565};
let state=load(),active=null,selected=new Set();
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function score(t){return state.topicScores?.[t.id]??t.score}function days(t){return state.lastReviewed?.[t.id]??t.last}function need(t){return Math.round((100-score(t))*.55+Math.min(days(t),21)*1.25+t.weight*7)}
function ranked(){return [...TOPICS].sort((a,b)=>need(b)-need(a)||score(a)-score(b))}function momentum(){return (state.weekMinutes||[]).filter(v=>v>=20).length}
function level(){const lv=Math.floor((state.xp||0)/400)+1,names=['Initiate','Initiate','Scholar','Scholar','Strategist','Strategist','Master'];return{lv,name:names[Math.min(lv-1,names.length-1)],need:lv*400-(state.xp||0),pct:Math.min(100,Math.round(((state.xp||0)-(lv-1)*400)/4))}}
function mount(){
  const host=q('#engagementMount');if(host)host.innerHTML='<div class="engagement-strip panel"><div><div class="eng-label">CURRENT LEVEL</div><div class="level-line"><strong id="missionLevelName"></strong><span id="missionLevelNo"></span></div><div class="xp-track"><i id="missionXpBar"></i></div><small id="missionXpText"></small></div><div><div class="eng-label">WEEKLY MOMENTUM</div><div class="momentum-line"><strong id="missionMomentum"></strong><span>sessions</span></div><div class="momentum-dots" id="missionDots"></div><small>No streak reset. Just keep the week moving.</small></div><div><div class="eng-label">PICK YOUR ENERGY</div><div class="mission-buttons"><button data-mission-mins="8">Quick <b>8m</b></button><button class="recommended" data-mission-mins="12">Standard <b>12m</b></button><button data-mission-mins="20">Challenge <b>20m</b></button></div><small>No choosing a topic. Revision HQ picks the move.</small></div></div>';
  document.body.insertAdjacentHTML('beforeend','<div class="mission-modal" id="missionModal" hidden><div class="mission-shell"><button class="mission-close" id="closeMission">×</button><div class="mission-run" id="missionRun"><div class="mission-topline"><span id="missionType"></span><span id="missionClock"></span></div><div class="mission-progress"><i class="on"></i><i></i></div><div class="mission-topic" id="missionTopic"></div><h2 id="missionPrompt"></h2><p class="mission-instruction" id="missionInstruction"></p><textarea id="missionAnswer" placeholder="Type from memory…"></textarea><button class="btn mission-primary" id="missionCheck">Check my recall →</button><div class="mission-check" id="missionCheckStage" hidden><div class="mission-check-head"><div><span>SELF-CHECK</span><h3>Which anchors did you actually cover?</h3></div><b id="missionBestLabel"></b></div><div class="mission-anchors" id="missionAnchors"></div><button class="btn mission-primary" id="missionFinish">Score mission →</button></div></div><div class="mission-result" id="missionResult" hidden><div class="result-burst">MISSION COMPLETE</div><h2 id="resultHeadline"></h2><div class="result-score"><strong id="resultScore"></strong><span>recall</span></div><div class="result-grid"><div><span>MASTERY</span><b id="resultMastery"></b></div><div><span>XP EARNED</span><b id="resultXp"></b></div><div><span>MOMENTUM</span><b id="resultMomentum"></b></div></div><div class="result-pb" id="resultPb" hidden>NEW PERSONAL BEST</div><p id="resultNext"></p><div class="result-actions"><button class="btn" id="missionDone">I’m done</button><button class="btn secondary" id="missionAgain">One more</button></div></div></div></div>');
  renderEngagement();bind();
}
function renderEngagement(){state=load();const l=level();q('#missionLevelName').textContent=l.name;q('#missionLevelNo').textContent=`Level ${l.lv}`;q('#missionXpBar').style.width=`${l.pct}%`;q('#missionXpText').textContent=`${l.need} XP to Level ${l.lv+1}`;q('#missionMomentum').textContent=`${momentum()} / 5`;q('#missionDots').innerHTML=Array.from({length:5},(_,i)=>`<i class="${i<momentum()?'on':''}"></i>`).join('');const top=q('#streakTop');if(top)top.textContent=`${momentum()} / 5`}
function nextTopic(){state=load();const r=ranked();return r.find(t=>t.id!==state.lastMissionTopic)||r[0]}
function missionType(){return ['RAPID RECALL','BEAT YOUR BEST','JUDGEMENT SPRINT'][(state.missionCount||0)%3]}
function startMission(mins){state=load();const t=nextTopic(),bank=BANK[t.id];active={t,bank,mins,old:score(t),type:missionType()};selected=new Set();q('#missionModal').hidden=false;q('#missionRun').hidden=false;q('#missionResult').hidden=true;q('#missionCheckStage').hidden=true;q('#missionAnswer').hidden=false;q('#missionAnswer').value='';q('#missionCheck').hidden=false;q('#missionType').textContent=active.type;q('#missionClock').textContent=`${mins} MIN`;q('#missionTopic').textContent=`${t.subject} · ${t.unit} · ${score(t)}% mastery`;q('#missionPrompt').textContent=bank.prompt;q('#missionInstruction').textContent=active.type==='BEAT YOUR BEST'?`Personal best: ${state.missionBests?.[t.id]??'—'}%. Beat it with clean recall, not longer notes.`:active.type==='JUDGEMENT SPRINT'?'Make the judgement first. Then add only the evidence that earns it.':'Three useful ideas beat a page of copied notes.';q('#missionBestLabel').textContent=`PB ${state.missionBests?.[t.id]??'—'}%`;q('#missionAnchors').innerHTML=bank.anchors.map((a,i)=>`<button class="mission-anchor" data-anchor="${i}"><i></i><span>${a}</span></button>`).join('');qa('.mission-progress i').forEach((e,i)=>e.classList.toggle('on',i===0));document.body.style.overflow='hidden'}
function closeMission(){q('#missionModal').hidden=true;document.body.style.overflow='';active=null;selected.clear()}
function bind(){
  [['#heroStart',12],['#topStart',12],['#tinyMission',5]].forEach(([sel,mins])=>{const el=q(sel);if(el)el.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();startMission(mins)},true)});
  qa('[data-mission-mins]').forEach(b=>b.addEventListener('click',()=>startMission(Number(b.dataset.missionMins))));q('#closeMission').addEventListener('click',closeMission);q('#missionModal').addEventListener('click',e=>{if(e.target===q('#missionModal'))closeMission()});
  q('#missionCheck').addEventListener('click',()=>{q('#missionAnswer').hidden=true;q('#missionCheck').hidden=true;q('#missionCheckStage').hidden=false;qa('.mission-progress i').forEach(x=>x.classList.add('on'));qa('.mission-anchor').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.anchor);selected.has(i)?selected.delete(i):selected.add(i);b.classList.toggle('selected',selected.has(i));b.querySelector('i').textContent=selected.has(i)?'✓':''}))});
  q('#missionFinish').addEventListener('click',finish);q('#missionDone').addEventListener('click',()=>{closeMission();location.reload()});q('#missionAgain').addEventListener('click',()=>startMission(active?.mins||8));
}
function finish(){if(!active)return;state=load();state.missionBests=state.missionBests||{};state.missionLog=state.missionLog||[];state.topicScores=state.topicScores||{};state.lastReviewed=state.lastReviewed||{};state.completedToday=state.completedToday||[];state.weekMinutes=state.weekMinutes||[0,0,0,0,0,0,0];const {t,bank,mins,old}=active,coverage=Math.round(selected.size/bank.anchors.length*100),gain=coverage>=100?4:coverage>=67?3:coverage>=34?2:1,newScore=Math.min(95,old+gain),xp=Math.round(35+mins*4+coverage*.55),prev=state.missionBests[t.id]??0,isPb=coverage>prev;state.topicScores[t.id]=newScore;state.lastReviewed[t.id]=0;state.xp=(state.xp||1180)+xp;state.missionCount=(state.missionCount||0)+1;state.missionBests[t.id]=Math.max(prev,coverage);state.lastMissionTopic=t.id;state.missionLog.push({date:todayKey(),topic:t.id,score:coverage,xp,mins});state.focusedMinutes=(state.focusedMinutes||0)+mins;const day=(new Date().getDay()+6)%7;state.weekMinutes[day]=(state.weekMinutes[day]||0)+mins;if(!state.completedToday.includes(t.id))state.completedToday.push(t.id);save();q('#missionRun').hidden=true;q('#missionResult').hidden=false;q('#resultScore').textContent=`${coverage}%`;q('#resultMastery').textContent=`${old} → ${newScore}`;q('#resultXp').textContent=`+${xp}`;q('#resultMomentum').textContent=`${momentum()} / 5`;q('#resultPb').hidden=!isPb;q('#resultHeadline').textContent=coverage>=85?'That was sharp.':coverage>=60?'Good work. The gaps are visible.':'Useful. Now you know what to repair.';const wait=coverage>=85?4:coverage>=60?2:1;q('#resultNext').textContent=`Next rematch: ${wait===1?'tomorrow':`in ${wait} days`} · ${coverage<60?'8':'12'} min.`;renderEngagement()}
mount();
})();
